version: 2
jobs:
  build:
    working_directory: ~/aerogear
    docker:
      # Node 8 LTS
      - image: circleci/node:carbon
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install
      - run:
          name: bootstrap project
          command: npm run bootstrap
      - run:
          name: compile
          command: npm run compile
      - run:
          name: test
          command: npm test
      - run:
          name: run lint
          command: npm run lint
  containers_publish:
    working_directory: ~/aerogear
    docker:
      # Node 8 LTS
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
          docker_layer_caching: true
      - run: |
          cd examples
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
          TAG=$CIRCLE_TAG ./push-script.sh basic
workflows:
  version: 2
  build_and_release:
    jobs:
      - containers_publish:
          filters:
            tags:
              only: /.*/
