version: 2
jobs:
  build:
    working_directory: ~/aerogear
    docker:
      # Node 8 LTS
      - image: circleci/node:carbon
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install
      - run:
          name: bootstrap project
          command: npm run bootstrap
      - run:
          name: compile
          command: npm run compile
      - run:
          name: test
          command: npm test
      - run:
          name: run lint
          command: npm run lint
  containers_publish:
    working_directory: ~/examples
    docker:
      # Node 8 LTS
      - image: circleci/node:carbon
    steps:
      - checkout
      - run: TAG=$CIRCLE_TAG ./push-script.sh basic
workflows:
  version: 2
  build_and_release:
    jobs:
      - containers_publish:
          filters:
            tags:
              only: /.*/
